services:
#  analyzer-service:
#    build: ./services/image-analyzer
#    
#    env_file:
#    - ./services/image-analyzer/.env
#    
#    ports:
#    - "5000:5000"

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
